### ISSUE TITLE
500 Internal Server Error attempting to add Netro Integration

### ISSUE THREAD

**Issue by kenwiens** [kcofoni/ha-netro-watering#12]
After adding netro custom component via HACS and rebooting HA, I attempt to add the integration.  I get an error "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble."

Running HA 2023.5.4 on RPi

I see nothing in the log files related to this.

![image](https://github.com/kcofoni/ha-netro-watering/assets/35972142/133dc0c4-0aa9-4989-b685-b3d1657581db)

**Comment by kcofoni** [comment]
Hi there !

Sorry for the inconvenience but no worries, I see exactly what it is. I had to change the versions of `requirements `since HA version  2023.6 due to upgrading to Python 3.11.

You have three options to fix this issue :
1. Upgrading your home assistant version to 2023.6 or higher. This is probably the best solution if you can do it.
2. As long as you stay in a version 2023.5 or lower, making the following change in the `manifest.json ` file located in the integration directory (`config/custom_components/netro_watering/manifest.json`). 
Change `requests==2.31.0` to `requests==2.28.2`
3. Installing version 1.1.0 or lower of this integration but frankly it would be a pity !

Keep me posted please.

**Comment by kenwiens** [comment]
I upgrade to 2023.6.2 and all is good.  Great work here!
